# Generated by Django 6.0.4 on 2026-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
